
import os

Import('env')

src = [
    "configuration.cc",
    "Debug/debug.cc",
    "Debug/pstats.cc",
    "Debug/stopwatch.cc",
    "Event/eventaio.cc",
    "Event/eventbuffer.cc",
    "Event/eventloop.cc",
    "Event/eventserversock.cc",
    "Event/eventsock.cc",
    "Event/eventtimer.cc",
    "Net/bufferedstream.cc",
    "Net/inet4address.cc",
    "Net/inetendpoint.cc",
    "Net/interface.cc",
    "Net/networkstream.cc",
    "Net/socket.cc",
    "Net/serversocket.cc",
    "Net/datagramsocket.cc",
    "Term/command.cc",
    "Term/shell.cc",
    "Term/terminal.cc",
    "Term/termui.cc",
    "MM/buddyalloc.cc",
    "skein/skein.c",
    "skein/skein_debug.c",
    "registry.cc",
	"HTTP/httpparser.cc",
	"HTTP/httpserver.cc",
	"HTTP/httpsession.cc",
]

if (os.uname()[4] == "amd64"):
    env.Append(CFLAGS = ["-DSKEIN_USE_ASM"])
    src.append("skein/amd64/skein_block_asm.s")
else:
    src.append("skein/skein_block.c")

env.StaticLibrary("CCore", src)

