Import('env')

src = [
    "diskalloc.cc",
    "bitmapalloc.cc",
    "blkptr.cc",
    "blockcache.cc",
    "btreealloc.cc",
    "dinode.cc",
    "vblkptr.cc",
    "dva.cc",
    "filedisk.cc",
    "diskosd.cc",
    "storagepool.cc",
    "transactiongroup.cc",
    "transactionmanager.cc",
    "sgarray.cc",
    "uberblock.cc",
    "util.cc",
    "diskvnode.cc",
    "memdisk.cc"
]

env.StaticLibrary("COSD", src)

