
Import('env')

fsck_celestis_env = env.Clone()

libs = [
    "COSD",
    "CCore",
    "stdc++",
]

srcs = [
    "main.cc"
]

fsck_celestis_env.Append(LIBS = libs)

fsck_celestis_env.Program("fsck_celestis", srcs)

