#ifndef __CELESTIS_FS_DEFINES_H__
#define __CELESTIS_FS_DEFINES_H__

#define KILOBYTE (1024)
#define MEGABYTE (1000 * KILOBYTE)
#define DEFAULT_BLOCK_SIZE (12) // 2 ^ 12
#define DEFAULT_CACHE_SIZE 100000
#define INODE_MAX_BLKPTR 15

#endif



